In [3]:
import numpy as np

def sma_multi(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C


A = np.array([[2, 4], [0, 5]]) 
B = np.array([[3, 2], [1, 6]])
C = square_matrix_multi(A, B)
print("Result:\n", C)
print("Time complexity is O(n^3) since there are 3 nested loops each iterating n times.")

Result:
 [[10 28]
 [ 5 30]]
Time complexity is O(n^3) since there are 3 nested loops each iterating n times.


In [6]:
def sma_mult_recursive(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=int)
    if n == 1:
        C[0, 0] = A[0, 0] * B[0, 0]
    else:
        A11, A12, A21, A22 = split_m(A)
        B11, B12, B21, B22 = split_m(B)
        C11 = sma_mult_recursive(A11, B11) + sma_mult_recursive(A12, B21)
        C12 = sma_mult_recursive(A11, B12) + sma_mult_recursive(A12, B22)
        C21 = sma_mult_recursive(A21, B11) + sma_mult_recursive(A22, B21)
        C22 = sma_mult_recursive(A21, B12) + sma_mult_recursive(A22, B22)
        C = combine_m(C11, C12, C21, C22)
    return C

def split_m(M):
    n = M.shape[0]//2
    M11 = M[:n, :n]
    M12 = M[:n, n:] 
    M21 = M[n:, :n]
    M22 = M[n:, n:]
    return M11, M12, M21, M22
    
def combine_m(C11, C12, C21, C22):
    n = C11.shape[0]
    C = np.zeros((2*n, 2*n), dtype=int)
    C[:n, :n] = C11
    C[:n, n:] = C12
    C[n:, :n] = C21 
    C[n:, n:] = C22
    return C
    

A = np.array([[6, 3, 10, 4], 
              [10, 3, 6, 10],
              [6, 9, 2, 5], 
              [4, 2, 9, 4]])

B = np.array([[8, 1, 6, 4],
              [7, 5, 9, 2], 
              [6, 3, 7, 8],
              [4, 9, 3, 1]])
              
C = sma_mult_recursive(A, B)
print("\nResult:\n", C)

print("""
Recursiveness: Base case is when n=1, a 1x1 matrix multiply；Recursion step divides matrices into quarters and multiplies quarters recursively；Recursion reduces to base case when matrices get divided all the way down to 1x1

Divide and Conquer:Split matrices A and B into 4 quarters each；Recursively multiply quarters；Add multiplied quarter results to get final matrix C

Complexity Analysis:Base case is O(1) when n=1；Divide step is O(1) as it just splits the matrices；Conquer step has 8 recursive calls of size n/2, so O(8*(n/2)^2) = O(n^2)；Combine step has 4 matrix additions of n/2 x n/2 matrices, so O(4*(n/2)^2) = O(n^2)
Putting it together using the master theorem, with a=8, b=2, f(n) = O(n^2):
T(n) = 8T(n/2) + O(n^2)
       = O(n^3) using case 2 of the master theorem       
So the overall time complexity is O(n^3), same as the iterative solution.
""")



Result:
 [[145  87 145 114]
 [177 133 159 104]
 [143 102 146  63]
 [116  77 117  96]]

Recursiveness: Base case is when n=1, a 1x1 matrix multiply；Recursion step divides matrices into quarters and multiplies quarters recursively；Recursion reduces to base case when matrices get divided all the way down to 1x1

Divide and Conquer:Split matrices A and B into 4 quarters each；Recursively multiply quarters；Add multiplied quarter results to get final matrix C

Complexity Analysis:Base case is O(1) when n=1；Divide step is O(1) as it just splits the matrices；Conquer step has 8 recursive calls of size n/2, so O(8*(n/2)^2) = O(n^2)；Combine step has 4 matrix additions of n/2 x n/2 matrices, so O(4*(n/2)^2) = O(n^2)
Putting it together using the master theorem, with a=8, b=2, f(n) = O(n^2):
T(n) = 8T(n/2) + O(n^2)
       = O(n^3) using case 2 of the master theorem       
So the overall time complexity is O(n^3), same as the iterative solution.



In [8]:
def strassen(A, B):
    n = A.shape[0]
    C = np.zeros((n, n), dtype=int)
    if n == 1:
        C[0, 0] = A[0, 0] * B[0, 0]
    else:
        A11, A12, A21, A22 = split_matrix(A)
        B11, B12, B21, B22 = split_matrix(B)
        S1 = B12 - B22
        S2 = A11 + A12
        S3 = A21 + A22
        S4 = B21 - B11
        S5 = A11 + A22
        S6 = B11 + B22
        S7 = A12 - A22
        S8 = B21 + B22  
        S9 = A11 - A21
        S10 = B11 + B12
        P1 = strassen(A11, S1)
        P2 = strassen(S2, B22)
        P3 = strassen(S3, B11)
        P4 = strassen(A22, S4)
        P5 = strassen(S5, S6)
        P6 = strassen(S7, S8)
        P7 = strassen(S9, S10)
        C11 = P5 + P4 - P2 + P6
        C12 = P1 + P2
        C21 = P3 + P4
        C22 = P5 + P1 - P3 - P7
        C = combine_matrix(C11, C12, C21, C22)
    return C

A = np.array([[6, 3, 10, 4], 
              [10, 3, 6, 10],
              [6, 9, 2, 5], 
              [4, 2, 9, 4]])
              
B = np.array([[8, 1, 6, 4],
              [7, 5, 9, 2], 
              [6, 3, 7, 8],
              [4, 9, 3, 1]])

C = strassen(A, B)
print("\nResult:\n", C)

print("""
Reflections:
Addition/subtraction are O(n^2) operations as just iterate through matrix once；Multiplication is O(n^3) with nested loops 

Complexity Analysis:
Base case is O(1) when n=1 ；Divide step has 7 multiplications of n/2 x n/2 = O(7*(n/2)^3) = O(n^3/8)；Conquer step has 10 additions of n/2 x n/2 = O(10*(n/2)^2) = O(5n^2/4) ；Combine step has 8 additions of n/2 x n/2 = O(8*(n/2)^2) = O(n^2)
Putting together using the master theorem, with a=7, b=2, f(n) = O(n^3/8) + O(5n^2/4) = O(n^3/4):
T(n) = 7T(n/2) + O(n^3/4)""")


Result:
 [[145  87 145 114]
 [177 133 159 104]
 [143 102 146  63]
 [116  77 117  96]]

Reflections:
Addition/subtraction are O(n^2) operations as just iterate through matrix once；Multiplication is O(n^3) with nested loops 

Complexity Analysis:
Base case is O(1) when n=1 ；Divide step has 7 multiplications of n/2 x n/2 = O(7*(n/2)^3) = O(n^3/8)；Conquer step has 10 additions of n/2 x n/2 = O(10*(n/2)^2) = O(5n^2/4) ；Combine step has 8 additions of n/2 x n/2 = O(8*(n/2)^2) = O(n^2)
Putting together using the master theorem, with a=7, b=2, f(n) = O(n^3/8) + O(5n^2/4) = O(n^3/4):
T(n) = 7T(n/2) + O(n^3/4)
